package plugin;

import terminalcommands.CommandHandler;

/**
 *
 * @author Austin
 */
public class Terminal extends javax.swing.JPanel {
    
    CommandHandler commandHandler;

    /**
     * Creates new form Terminal
     */
    public Terminal() {
        commandHandler = new CommandHandler();
        initComponents();
        inputArea.setText(">");
    }

    public int lastIndexOf(String string, String substring) {
        String reversedString = "";
        for (int i = 0; i < string.length(); i++) {
            reversedString = string.charAt(i) + reversedString;
        }

        String reversedSubstring = "";
        for (int i = 0; i < substring.length(); i++) {
            reversedSubstring = substring.charAt(i) + reversedSubstring;
        }

        int reversedIndex = reversedString.indexOf(reversedSubstring);
        int index = -1;
        if (reversedIndex != -1) {
            index = string.length() - (reversedIndex + substring.length());
        }

        return index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();

        inputArea.setColumns(20);
        inputArea.setRows(5);
        inputArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(inputArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAreaKeyTyped
        if (evt.getKeyChar() == '\n') {
            inputArea.setText(inputArea.getText().substring(
                    0, inputArea.getCaretPosition() - 1)
                    + inputArea.getText().substring(
                    inputArea.getCaretPosition()));
            String command = inputArea.getText().
                    substring(lastIndexOf(inputArea.getText(), ">") + 1);
            String message = commandHandler.executeCommand(command);
            inputArea.setText(inputArea.getText() + "\n" + message + ">");
            inputArea.setCaretPosition(inputArea.getText().length());
        }
    }//GEN-LAST:event_inputAreaKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
