package plugin;

import com.coderedrobotics.dashboard.communications.DSMListener;
import com.coderedrobotics.dashboard.communications.DataStream;
import com.coderedrobotics.dashboard.communications.DataStreamingModule;
import com.coderedrobotics.dashboard.communications.Packet;
import com.coderedrobotics.dashboard.communications.SynchronizedRegisterArray;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;

/**
 *
 * @author Austin
 */
public class DebugConsole extends javax.swing.JPanel implements DSMListener {

    DataStreamingModule dataStreamingModule;
    SynchronizedRegisterArray synchronizedRegisterArray;
    int oldLength = 0;

    /**
     * Creates new form DebugConsole
     */
    public DebugConsole() {
        initComponents();
    }

    public void init(DataStreamingModule dataStreamingModule,
            SynchronizedRegisterArray synchronizedRegisterArray) {
        this.dataStreamingModule = dataStreamingModule;
        this.synchronizedRegisterArray = synchronizedRegisterArray;
        dataStreamingModule.addDSMListener(this);
    }

    @Override
    public void alertToDSMUpdates() {
        DataStream ds = dataStreamingModule.getStream("DEBUG");
        if (ds != null) {
            try {
                int dif = ds.getPackets().length - oldLength;
                while (ds != null && dif > 0) {
                    Document document = jTextPane1.getDocument();

                    document.insertString(document.getLength(), "" + ((char) ds.getPackets()[dif - 1].val), new SimpleAttributeSet());
                    jTextPane1.setCaretPosition(document.getLength());

                    // = ds.getPackets().length;
//            String s = "";
//            Packet[] p = ds.getPackets();
//            for (int i = 0; i < p.length; i++) {
//                s = ((char) p[i].val) + s;
//            }
                    oldLength++;
                    dif = ds.getPackets().length - oldLength;
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(DebugConsole.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public void alertToNewStreams() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        debugChannel = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jLabel1.setText("Debug Channel");

        debugChannel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                debugChannelStateChanged(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(debugChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debugChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void debugChannelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_debugChannelStateChanged
        synchronizedRegisterArray.setRegister("DEBUGCHANNEL",
                Double.parseDouble(debugChannel.getValue().toString()));
    }//GEN-LAST:event_debugChannelStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner debugChannel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
