package com.coderedrobotics.virtualrobot;

import com.coderedrobotics.dashboard.communications.Connection;
import com.coderedrobotics.dashboard.communications.PrimitiveSerializer;
import com.coderedrobotics.dashboard.communications.Subsocket;
import com.coderedrobotics.dashboard.communications.exceptions.InvalidRouteException;
import com.coderedrobotics.dashboard.communications.exceptions.NotMultiplexedException;

/**
 *
 * @author Michael
 */
public class GUI extends javax.swing.JPanel {

    Subsocket dio;
    Subsocket analogin;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setup();
    }

    private void setup() {
        try {
            Subsocket virtualrobot = Connection.getInstance().getRootSubsocket().enableMultiplexing().createNewRoute("root.virtualrobot").enableMultiplexing();
            dio = Connection.getInstance().getRootSubsocket().createNewRoute("root.virtualrobot.dio");
            analogin = Connection.getInstance().getRootSubsocket().createNewRoute("root.virtualrobot.analogin");
        } catch (NotMultiplexedException | InvalidRouteException ex) {
            ex.printStackTrace();
        }
        relay1back.setup("root.virtualrobot.r1b");
        relay1forward.setup("root.virtualrobot.r1f");
        relay2back.setup("root.virtualrobot.r2b");
        relay2forward.setup("root.virtualrobot.r2f");
        relay3back.setup("root.virtualrobot.r3b");
        relay3forward.setup("root.virtualrobot.r3f");
        relay4back.setup("root.virtualrobot.r4b");
        relay4forward.setup("root.virtualrobot.r4f");
        pwm0.setup("root.virtualrobot.pwm0", false);
        pwm1.setup("root.virtualrobot.pwm1", false);
        pwm2.setup("root.virtualrobot.pwm2", false);
        pwm3.setup("root.virtualrobot.pwm3", false);
        pwm4.setup("root.virtualrobot.pwm4", false);
        pwm5.setup("root.virtualrobot.pwm5", false);
        pwm6.setup("root.virtualrobot.pwm6", false);
        pwm7.setup("root.virtualrobot.pwm7", false);
        pwm8.setup("root.virtualrobot.pwm8", false);
        pwm9.setup("root.virtualrobot.pwm9", false);
        pneumatics0back.setup("root.virtualrobot.pneumatics0b");
        pneumatics0forward.setup("root.virtualrobot.pneumatics0f");
        pneumatics1back.setup("root.virtualrobot.pneumatics1b");
        pneumatics1forward.setup("root.virtualrobot.pneumatics1f");
        pneumatics2back.setup("root.virtualrobot.pneumatics2b");
        pneumatics2forward.setup("root.virtualrobot.pneumatics2f");
        pneumatics3back.setup("root.virtualrobot.pneumatics3b");
        pneumatics3forward.setup("root.virtualrobot.pneumatics3f");
        pneumatics4back.setup("root.virtualrobot.pneumatics4b");
        pneumatics4forward.setup("root.virtualrobot.pneumatics4f");
        pneumatics5back.setup("root.virtualrobot.pneumatics5b");
        pneumatics5forward.setup("root.virtualrobot.pneumatics5f");
        pneumatics6back.setup("root.virtualrobot.pneumatics6b");
        pneumatics6forward.setup("root.virtualrobot.pneumatics6f");
        pneumatics7back.setup("root.virtualrobot.pneumatics7b");
        pneumatics7forward.setup("root.virtualrobot.pneumatics7f");
        compressor.setup("root.virtualrobot.compressor");
        pwm0.enablePWMMode(true);
        pwm1.enablePWMMode(true);
        pwm2.enablePWMMode(true);
        pwm3.enablePWMMode(true);
        pwm4.enablePWMMode(true);
        pwm5.enablePWMMode(true);
        pwm6.enablePWMMode(true);
        pwm7.enablePWMMode(true);
        pwm8.enablePWMMode(true);
        pwm9.enablePWMMode(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dio9 = new javax.swing.JCheckBox();
        dio8 = new javax.swing.JCheckBox();
        dio7 = new javax.swing.JCheckBox();
        dio6 = new javax.swing.JCheckBox();
        dio5 = new javax.swing.JCheckBox();
        dio4 = new javax.swing.JCheckBox();
        dio3 = new javax.swing.JCheckBox();
        dio2 = new javax.swing.JCheckBox();
        dio1 = new javax.swing.JCheckBox();
        dio0 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        analogIn1 = new javax.swing.JSlider();
        analogIn2 = new javax.swing.JSlider();
        analogIn3 = new javax.swing.JSlider();
        analogIn4 = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        relay1back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        relay1forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        relay4forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        relay4back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        relay3forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        relay3back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        relay2forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        relay2back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jPanel5 = new javax.swing.JPanel();
        pwm0 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel11 = new javax.swing.JLabel();
        pwm1 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel12 = new javax.swing.JLabel();
        pwm2 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel13 = new javax.swing.JLabel();
        pwm3 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel14 = new javax.swing.JLabel();
        pwm4 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel15 = new javax.swing.JLabel();
        pwm9 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel16 = new javax.swing.JLabel();
        pwm8 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pwm7 = new com.coderedrobotics.dashboard.api.gui.Bar();
        pwm6 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pwm5 = new com.coderedrobotics.dashboard.api.gui.Bar();
        jPanel6 = new javax.swing.JPanel();
        pneumatics0forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics0back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel21 = new javax.swing.JLabel();
        pneumatics1forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics1back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel22 = new javax.swing.JLabel();
        pneumatics2forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics2back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel23 = new javax.swing.JLabel();
        pneumatics3forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics3back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel24 = new javax.swing.JLabel();
        pneumatics7back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics7forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel25 = new javax.swing.JLabel();
        pneumatics6back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics6forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pneumatics5back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics5forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics4forward = new com.coderedrobotics.dashboard.api.gui.Indicator();
        pneumatics4back = new com.coderedrobotics.dashboard.api.gui.Indicator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        compressor = new com.coderedrobotics.dashboard.api.gui.Indicator();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Digital I/O"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        dio9.setText("9");
        dio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio9ActionPerformed(evt);
            }
        });

        dio8.setText("8");
        dio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio8ActionPerformed(evt);
            }
        });

        dio7.setText("7");
        dio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio7ActionPerformed(evt);
            }
        });

        dio6.setText("6");
        dio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio6ActionPerformed(evt);
            }
        });

        dio5.setText("5");
        dio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio5ActionPerformed(evt);
            }
        });

        dio4.setText("4");
        dio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio4ActionPerformed(evt);
            }
        });

        dio3.setText("3");
        dio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio3ActionPerformed(evt);
            }
        });

        dio2.setText("2");
        dio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio2ActionPerformed(evt);
            }
        });

        dio1.setText("1");
        dio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio1ActionPerformed(evt);
            }
        });

        dio0.setText("0");
        dio0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dio0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dio0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dio9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dio0)
            .addComponent(dio1)
            .addComponent(dio2)
            .addComponent(dio3)
            .addComponent(dio4)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dio5)
                .addComponent(dio6)
                .addComponent(dio7)
                .addComponent(dio8)
                .addComponent(dio9))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Analog IN 1:");

        jLabel4.setText("Analog IN 2:");

        jLabel5.setText("Analog IN 3:");

        jLabel6.setText("Analog IN 4:");

        analogIn1.setMajorTickSpacing(15);
        analogIn1.setMaximum(150);
        analogIn1.setMinorTickSpacing(15);
        analogIn1.setToolTipText("");
        analogIn1.setValue(0);
        analogIn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                analogIn1StateChanged(evt);
            }
        });

        analogIn2.setMajorTickSpacing(15);
        analogIn2.setMaximum(150);
        analogIn2.setMinorTickSpacing(15);
        analogIn2.setToolTipText("");
        analogIn2.setValue(0);
        analogIn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                analogIn2StateChanged(evt);
            }
        });

        analogIn3.setMajorTickSpacing(15);
        analogIn3.setMaximum(150);
        analogIn3.setMinorTickSpacing(15);
        analogIn3.setToolTipText("");
        analogIn3.setValue(0);
        analogIn3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                analogIn3StateChanged(evt);
            }
        });

        analogIn4.setMajorTickSpacing(15);
        analogIn4.setMaximum(150);
        analogIn4.setMinorTickSpacing(15);
        analogIn4.setToolTipText("");
        analogIn4.setValue(0);
        analogIn4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                analogIn4StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(analogIn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analogIn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(analogIn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(analogIn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(analogIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(analogIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(analogIn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(analogIn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Relay 4");

        jLabel9.setText("Relay 3");

        jLabel8.setText("Relay 2");

        jLabel7.setText("Relay 1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(relay4back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relay4forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(relay1back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relay1forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(relay3back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relay3forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(relay2back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relay2forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relay1forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(relay1back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(relay2back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(relay2forward, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(relay3back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(relay3forward, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(relay4back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(relay4forward, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pwm0Layout = new javax.swing.GroupLayout(pwm0);
        pwm0.setLayout(pwm0Layout);
        pwm0Layout.setHorizontalGroup(
            pwm0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm0Layout.setVerticalGroup(
            pwm0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PWM 0");

        javax.swing.GroupLayout pwm1Layout = new javax.swing.GroupLayout(pwm1);
        pwm1.setLayout(pwm1Layout);
        pwm1Layout.setHorizontalGroup(
            pwm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm1Layout.setVerticalGroup(
            pwm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PWM 1");

        javax.swing.GroupLayout pwm2Layout = new javax.swing.GroupLayout(pwm2);
        pwm2.setLayout(pwm2Layout);
        pwm2Layout.setHorizontalGroup(
            pwm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm2Layout.setVerticalGroup(
            pwm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PWM 2");

        javax.swing.GroupLayout pwm3Layout = new javax.swing.GroupLayout(pwm3);
        pwm3.setLayout(pwm3Layout);
        pwm3Layout.setHorizontalGroup(
            pwm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm3Layout.setVerticalGroup(
            pwm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PWM 3");

        javax.swing.GroupLayout pwm4Layout = new javax.swing.GroupLayout(pwm4);
        pwm4.setLayout(pwm4Layout);
        pwm4Layout.setHorizontalGroup(
            pwm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm4Layout.setVerticalGroup(
            pwm4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PWM 4");

        javax.swing.GroupLayout pwm9Layout = new javax.swing.GroupLayout(pwm9);
        pwm9.setLayout(pwm9Layout);
        pwm9Layout.setHorizontalGroup(
            pwm9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm9Layout.setVerticalGroup(
            pwm9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PWM 9");

        javax.swing.GroupLayout pwm8Layout = new javax.swing.GroupLayout(pwm8);
        pwm8.setLayout(pwm8Layout);
        pwm8Layout.setHorizontalGroup(
            pwm8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm8Layout.setVerticalGroup(
            pwm8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PWM 8");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PWM 7");

        javax.swing.GroupLayout pwm7Layout = new javax.swing.GroupLayout(pwm7);
        pwm7.setLayout(pwm7Layout);
        pwm7Layout.setHorizontalGroup(
            pwm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm7Layout.setVerticalGroup(
            pwm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pwm6Layout = new javax.swing.GroupLayout(pwm6);
        pwm6.setLayout(pwm6Layout);
        pwm6Layout.setHorizontalGroup(
            pwm6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm6Layout.setVerticalGroup(
            pwm6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PWM 6");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("PWM 5");

        javax.swing.GroupLayout pwm5Layout = new javax.swing.GroupLayout(pwm5);
        pwm5.setLayout(pwm5Layout);
        pwm5Layout.setHorizontalGroup(
            pwm5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pwm5Layout.setVerticalGroup(
            pwm5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwm9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwm0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwm8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pneumatics"));

        jLabel21.setText("0");

        jLabel22.setText("1");

        jLabel23.setText("2");

        jLabel24.setText("3");

        jLabel25.setText("7");

        jLabel26.setText("6");

        jLabel27.setText("5");

        jLabel28.setText("4");

        jLabel29.setText("Compressor");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics0back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics0forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics1back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics1forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics2back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics2forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics3back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics3forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics4back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics4forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics5back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics5forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics6back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics6forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics7back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pneumatics7forward, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(compressor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics0forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(pneumatics0back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics1forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(pneumatics1back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics2forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(pneumatics2back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics3forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(pneumatics3back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics4forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(pneumatics4back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics5forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(pneumatics5back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics6forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(pneumatics6back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pneumatics7forward, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(pneumatics7back, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compressor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dio0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio0ActionPerformed
        byte[] data = {0, (byte) (dio0.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio0ActionPerformed

    private void dio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio1ActionPerformed
        byte[] data = {1, (byte) (dio1.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio1ActionPerformed

    private void dio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio2ActionPerformed
        byte[] data = {2, (byte) (dio2.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio2ActionPerformed

    private void dio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio3ActionPerformed
        byte[] data = {3, (byte) (dio3.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio3ActionPerformed

    private void dio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio4ActionPerformed
        byte[] data = {4, (byte) (dio4.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio4ActionPerformed

    private void dio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio5ActionPerformed
        byte[] data = {5, (byte) (dio5.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio5ActionPerformed

    private void dio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio6ActionPerformed
        byte[] data = {6, (byte) (dio6.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio6ActionPerformed

    private void dio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio7ActionPerformed
        byte[] data = {7, (byte) (dio7.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio7ActionPerformed

    private void dio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio8ActionPerformed
        byte[] data = {8, (byte) (dio8.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio8ActionPerformed

    private void dio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dio9ActionPerformed
        byte[] data = {9, (byte) (dio9.isSelected() ? 1 : 0)};
        dio.sendData(data);
    }//GEN-LAST:event_dio9ActionPerformed

    private void analogIn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_analogIn1StateChanged
        byte[] data = new byte[9];
        data[0] = 1;
        System.arraycopy(PrimitiveSerializer.toByteArray(analogIn1.getValue() / 10d), 0, data, 1, 8);
        analogin.sendData(data);
    }//GEN-LAST:event_analogIn1StateChanged

    private void analogIn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_analogIn2StateChanged
        byte[] data = new byte[9];
        data[0] = 2;
        System.arraycopy(PrimitiveSerializer.toByteArray(analogIn2.getValue() / 10d), 0, data, 1, 8);
        analogin.sendData(data);
    }//GEN-LAST:event_analogIn2StateChanged

    private void analogIn3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_analogIn3StateChanged
        byte[] data = new byte[9];
        data[0] = 3;
        System.arraycopy(PrimitiveSerializer.toByteArray(analogIn3.getValue() / 10d), 0, data, 1, 8);
        analogin.sendData(data);
    }//GEN-LAST:event_analogIn3StateChanged

    private void analogIn4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_analogIn4StateChanged
        byte[] data = new byte[9];
        data[0] = 4;
        System.arraycopy(PrimitiveSerializer.toByteArray(analogIn4.getValue() / 10d), 0, data, 1, 8);
        analogin.sendData(data);
    }//GEN-LAST:event_analogIn4StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider analogIn1;
    private javax.swing.JSlider analogIn2;
    private javax.swing.JSlider analogIn3;
    private javax.swing.JSlider analogIn4;
    private com.coderedrobotics.dashboard.api.gui.Indicator compressor;
    private javax.swing.JCheckBox dio0;
    private javax.swing.JCheckBox dio1;
    private javax.swing.JCheckBox dio2;
    private javax.swing.JCheckBox dio3;
    private javax.swing.JCheckBox dio4;
    private javax.swing.JCheckBox dio5;
    private javax.swing.JCheckBox dio6;
    private javax.swing.JCheckBox dio7;
    private javax.swing.JCheckBox dio8;
    private javax.swing.JCheckBox dio9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics0back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics0forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics1back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics1forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics2back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics2forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics3back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics3forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics4back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics4forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics5back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics5forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics6back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics6forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics7back;
    private com.coderedrobotics.dashboard.api.gui.Indicator pneumatics7forward;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm0;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm1;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm2;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm3;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm4;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm5;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm6;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm7;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm8;
    private com.coderedrobotics.dashboard.api.gui.Bar pwm9;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay1back;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay1forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay2back;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay2forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay3back;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay3forward;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay4back;
    private com.coderedrobotics.dashboard.api.gui.Indicator relay4forward;
    // End of variables declaration//GEN-END:variables

}
